export const genres = [
    'Fantasy',
    'Science Fiction',
    'Dystopian',
    'Adventure',
    'Romance',
    'Contemporary',
    'Mystery',
    'Thriller',
    'Horror',
    'Historical Fiction',
    'Magical Realism',
    'Graphic Novels',
    'Young Adult (YA)',
    'Children\'s Fiction',
    'Fairy Tales',
    'Paranormal',
    'Crime',
    'Urban Fantasy',
    'Literary Fiction',
    'Speculative Fiction',
    'Biography',
    'Autobiography',
    'Memoir',
    'Self-help',
    'Cookbooks',
    'History',
    'True Crime',
    'Science',
    'Travel',
  ];
  